### ISSUE TITLE
Corrupt display of TIFF file

### ISSUE THREAD

**Issue by howff** [delhoume/vliv#2]
I have an example TIFF file which displays perfectly, except at the very bottom of the image where VLIV has inserted a black stripe. The same image displayed in IrfanView is how I expect, without the black stripe.

![image](https://user-images.githubusercontent.com/3064316/151263447-b9091bbc-5a71-495d-bdd8-403017b51bce.png)

(VLIV on the left, IrfanView underneath on the right)

**Comment by delhoume** [comment]
Do you have a link to the TIFF image ?
Is it the only one with a bad display ?
And what is the VLIV version ?

**Comment by howff** [comment]
VLIV is 2.5.4 (latest).
TIFF is here: https://we.tl/t-LdDBgvXtYK
I haven't tried any others yet.

**Comment by delhoume** [comment]
I reproduce the issue, working on it...

**Comment by delhoume** [comment]
Vliv 2.5.5 fixes the issue, please test

**Comment by howff** [comment]
v2.5.5 does display the image properly, thank you for the quick fix :-)
(I don't see any source code changes in the repo though, apart from the version number!).

I also like the zoom through pyramids feature, very useful. I will have to try it on a cloud-optimised GeoTIFF next.

**Comment by delhoume** [comment]
The fix is in the plugins repo : https://github.com/delhoume/vlivplugins.

I might have to make different versions and releases for Vliv and its plugins
