### ISSUE TITLE
Zoom problem

### ISSUE THREAD

**Issue by AbdurrahimDerric0** [delhoume/vliv#5]
Hi, what are the keys used to zoom in and out in the UI?

kind regards.

**Comment by delhoume** [comment]
vliv is not a standard viewer, zooming in and out are available only for specific image formats, for example TIFFs that are specially processed with pyramidal levels. (and Jpeg) with arbitrary unzoom levels. In Vliv context these are called pages.
You will find the shortcuts in the image menu.
If the image format does not comply with this notion of pages, you will not be able to zoom in or out.
If you want to be able to zoom in/out freely in any image, it is better to use another viewer.

For jpeg images, Vliv uses the ability to load different levels in the libJPEG API.

Remember that the first usage of Vliv is to display gigapixel TIFFs
