### ISSUE TITLE
license for source

### ISSUE THREAD

**Issue by phanirithvij** [delhoume/vliv#7]
What is the license for the source code?

**Comment by delhoume** [comment]
"This code is free"

You can do whatever you want with it

**Comment by phanirithvij** [comment]
Thank you for the quick response.

From my understanding some people might not be satisfied with just that clause, from what I read on https://opensource.stackexchange.com/a/1721/16174 and elsewhere, it is best if a specific license is mentioned so as to avoid any headaches.
Here are some https://opensource.org/licenses.
I suggest the MIT License which is the least restrictive of all.
