### ISSUE TITLE
Is it possible to use it in linux?

### ISSUE THREAD

**Issue by adammaj1** [delhoume/vliv#9]
Probably using wine. WHich parts of code are windows specific?

**Comment by delhoume** [comment]
I tested Vliv on Wine for MacOSX and it worked. Should also work on Linux.
Almost every line of code is Win32 specific, in fact it has been written as an exercise in Win32 pure C coding ;-).

The principle behind Vliv (only load parts of the image that is visible, and leverage the TIFF format - tiled pyramidal images) can be implemented on any OS. The API for plugins consists only of 5 functions, see the vlivplugins repo for examples.
